name: callingitnow
services:
- name: web
  source_dir: frontend
  github:
    repo: acforster/callingitnow
    branch: main
  build_command: npm run build
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: NEXT_PUBLIC_API_BASE
    value: ${api.PUBLIC_URL}
  - key: NODE_ENV
    value: production

- name: api
  source_dir: backend
  github:
    repo: acforster/callingitnow
    branch: main
  build_command: pip install -r requirements.txt
  run_command: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /api
    preserve_path_prefix: true
  envs:
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
  - key: JWT_SECRET
    value: ${JWT_SECRET}
  - key: JWT_ALGORITHM
    value: HS256
  - key: JWT_EXPIRE_MINUTES
    value: "30"
  - key: GOOGLE_OAUTH_CLIENT_ID
    value: ${GOOGLE_OAUTH_CLIENT_ID}
  - key: GOOGLE_OAUTH_CLIENT_SECRET
    value: ${GOOGLE_OAUTH_CLIENT_SECRET}
  - key: ALLOWED_ORIGINS
    value: ${web.PUBLIC_URL},https://callingitnow.com,https://www.callingitnow.com
  - key: RATE_LIMIT_PER_MINUTE
    value: "60"
  - key: CONTENT_FILTER_LEVEL
    value: PG13
  - key: DEBUG
    value: "false"
  - key: LOG_LEVEL
    value: info

databases:
- name: db
  engine: PG
  num_nodes: 1
  size: db-s-dev-database
  version: "15"

domains:
- domain: callingitnow.com
  type: PRIMARY
- domain: www.callingitnow.com
  type: ALIAS
